### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [Mashape/docker-kong#98] opened 2017-08-17 09:12 UTC
I want to build this image on arm64 architecture,but I'm not sure that can be support arm64 architecture https://bintray.com/kong/kong-community-edition-rpm/download_file?file_path=dists%2Fkong-community-edition-0.11.0.el7.noarch.rpm

**Comment by thefosk** [comment] 2017-09-11 23:43
Duplicate of #39.

**Closed by thefosk** 2017-09-11 23:43 UTC
